# Generated by Django 4.2.3 on 2023-09-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minuts',
            new_name='time_minutes',
        ),
    ]
